// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/dbexp.proto

package dbexpv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DBExpService_CheckHealth_FullMethodName = "/dbexp.v1.DBExpService/CheckHealth"
	DBExpService_UpsertPost_FullMethodName  = "/dbexp.v1.DBExpService/UpsertPost"
	DBExpService_ReadPost_FullMethodName    = "/dbexp.v1.DBExpService/ReadPost"
)

// DBExpServiceClient is the client API for DBExpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DBExpService defines the backend APIs for interacting with the database.
type DBExpServiceClient interface {
	// 1. Health check API
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error)
	// 2. UpsertPost API
	UpsertPost(ctx context.Context, in *UpsertPostRequest, opts ...grpc.CallOption) (*UpsertPostResponse, error)
	// 3. ReadPost API
	ReadPost(ctx context.Context, in *ReadPostRequest, opts ...grpc.CallOption) (*ReadPostResponse, error)
}

type dBExpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDBExpServiceClient(cc grpc.ClientConnInterface) DBExpServiceClient {
	return &dBExpServiceClient{cc}
}

func (c *dBExpServiceClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckHealthResponse)
	err := c.cc.Invoke(ctx, DBExpService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBExpServiceClient) UpsertPost(ctx context.Context, in *UpsertPostRequest, opts ...grpc.CallOption) (*UpsertPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertPostResponse)
	err := c.cc.Invoke(ctx, DBExpService_UpsertPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBExpServiceClient) ReadPost(ctx context.Context, in *ReadPostRequest, opts ...grpc.CallOption) (*ReadPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadPostResponse)
	err := c.cc.Invoke(ctx, DBExpService_ReadPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBExpServiceServer is the server API for DBExpService service.
// All implementations must embed UnimplementedDBExpServiceServer
// for forward compatibility.
//
// DBExpService defines the backend APIs for interacting with the database.
type DBExpServiceServer interface {
	// 1. Health check API
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error)
	// 2. UpsertPost API
	UpsertPost(context.Context, *UpsertPostRequest) (*UpsertPostResponse, error)
	// 3. ReadPost API
	ReadPost(context.Context, *ReadPostRequest) (*ReadPostResponse, error)
	mustEmbedUnimplementedDBExpServiceServer()
}

// UnimplementedDBExpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBExpServiceServer struct{}

func (UnimplementedDBExpServiceServer) CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedDBExpServiceServer) UpsertPost(context.Context, *UpsertPostRequest) (*UpsertPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertPost not implemented")
}
func (UnimplementedDBExpServiceServer) ReadPost(context.Context, *ReadPostRequest) (*ReadPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPost not implemented")
}
func (UnimplementedDBExpServiceServer) mustEmbedUnimplementedDBExpServiceServer() {}
func (UnimplementedDBExpServiceServer) testEmbeddedByValue()                      {}

// UnsafeDBExpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBExpServiceServer will
// result in compilation errors.
type UnsafeDBExpServiceServer interface {
	mustEmbedUnimplementedDBExpServiceServer()
}

func RegisterDBExpServiceServer(s grpc.ServiceRegistrar, srv DBExpServiceServer) {
	// If the following call panics, it indicates UnimplementedDBExpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBExpService_ServiceDesc, srv)
}

func _DBExpService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBExpServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBExpService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBExpServiceServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBExpService_UpsertPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBExpServiceServer).UpsertPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBExpService_UpsertPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBExpServiceServer).UpsertPost(ctx, req.(*UpsertPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBExpService_ReadPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBExpServiceServer).ReadPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBExpService_ReadPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBExpServiceServer).ReadPost(ctx, req.(*ReadPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DBExpService_ServiceDesc is the grpc.ServiceDesc for DBExpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBExpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbexp.v1.DBExpService",
	HandlerType: (*DBExpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _DBExpService_CheckHealth_Handler,
		},
		{
			MethodName: "UpsertPost",
			Handler:    _DBExpService_UpsertPost_Handler,
		},
		{
			MethodName: "ReadPost",
			Handler:    _DBExpService_ReadPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dbexp.proto",
}
