// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/dbexp.proto

package dbexpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_proto_dbexp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbexp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbexp_proto_rawDescGZIP(), []int{0}
}

type CheckHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard HTTP-like status codes: 200 (Success), 500 (Internal Error)
	StatusCode    int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_proto_dbexp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbexp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbexp_proto_rawDescGZIP(), []int{1}
}

func (x *CheckHealthResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CheckHealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpsertPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPostRequest) Reset() {
	*x = UpsertPostRequest{}
	mi := &file_proto_dbexp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPostRequest) ProtoMessage() {}

func (x *UpsertPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbexp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPostRequest.ProtoReflect.Descriptor instead.
func (*UpsertPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbexp_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpsertPostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpsertPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpsertPostRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type UpsertPostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard HTTP-like status codes: 200 (Success), 500 (Internal Error)
	StatusCode    int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPostResponse) Reset() {
	*x = UpsertPostResponse{}
	mi := &file_proto_dbexp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPostResponse) ProtoMessage() {}

func (x *UpsertPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbexp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPostResponse.ProtoReflect.Descriptor instead.
func (*UpsertPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbexp_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertPostResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpsertPostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPostRequest) Reset() {
	*x = ReadPostRequest{}
	mi := &file_proto_dbexp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPostRequest) ProtoMessage() {}

func (x *ReadPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbexp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPostRequest.ProtoReflect.Descriptor instead.
func (*ReadPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbexp_proto_rawDescGZIP(), []int{4}
}

func (x *ReadPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type ReadPostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard HTTP-like status codes: 200 (Success), 500 (Internal Error)
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Post data (empty if status_code is 500)
	PostId        string `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Title         string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Author        string `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPostResponse) Reset() {
	*x = ReadPostResponse{}
	mi := &file_proto_dbexp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPostResponse) ProtoMessage() {}

func (x *ReadPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbexp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPostResponse.ProtoReflect.Descriptor instead.
func (*ReadPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbexp_proto_rawDescGZIP(), []int{5}
}

func (x *ReadPostResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ReadPostResponse) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ReadPostResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReadPostResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReadPostResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_proto_dbexp_proto protoreflect.FileDescriptor

const file_proto_dbexp_proto_rawDesc = "" +
	"\n" +
	"\x11proto/dbexp.proto\x12\bdbexp.v1\"\x14\n" +
	"\x12CheckHealthRequest\"P\n" +
	"\x13CheckHealthResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\x11UpsertPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\"O\n" +
	"\x12UpsertPostResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x0fReadPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"\x94\x01\n" +
	"\x10ReadPostResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author2\xe6\x01\n" +
	"\fDBExpService\x12J\n" +
	"\vCheckHealth\x12\x1c.dbexp.v1.CheckHealthRequest\x1a\x1d.dbexp.v1.CheckHealthResponse\x12G\n" +
	"\n" +
	"UpsertPost\x12\x1b.dbexp.v1.UpsertPostRequest\x1a\x1c.dbexp.v1.UpsertPostResponse\x12A\n" +
	"\bReadPost\x12\x19.dbexp.v1.ReadPostRequest\x1a\x1a.dbexp.v1.ReadPostResponseB&Z$dbexp/backend/proto/dbexp/v1;dbexpv1b\x06proto3"

var (
	file_proto_dbexp_proto_rawDescOnce sync.Once
	file_proto_dbexp_proto_rawDescData []byte
)

func file_proto_dbexp_proto_rawDescGZIP() []byte {
	file_proto_dbexp_proto_rawDescOnce.Do(func() {
		file_proto_dbexp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dbexp_proto_rawDesc), len(file_proto_dbexp_proto_rawDesc)))
	})
	return file_proto_dbexp_proto_rawDescData
}

var file_proto_dbexp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_dbexp_proto_goTypes = []any{
	(*CheckHealthRequest)(nil),  // 0: dbexp.v1.CheckHealthRequest
	(*CheckHealthResponse)(nil), // 1: dbexp.v1.CheckHealthResponse
	(*UpsertPostRequest)(nil),   // 2: dbexp.v1.UpsertPostRequest
	(*UpsertPostResponse)(nil),  // 3: dbexp.v1.UpsertPostResponse
	(*ReadPostRequest)(nil),     // 4: dbexp.v1.ReadPostRequest
	(*ReadPostResponse)(nil),    // 5: dbexp.v1.ReadPostResponse
}
var file_proto_dbexp_proto_depIdxs = []int32{
	0, // 0: dbexp.v1.DBExpService.CheckHealth:input_type -> dbexp.v1.CheckHealthRequest
	2, // 1: dbexp.v1.DBExpService.UpsertPost:input_type -> dbexp.v1.UpsertPostRequest
	4, // 2: dbexp.v1.DBExpService.ReadPost:input_type -> dbexp.v1.ReadPostRequest
	1, // 3: dbexp.v1.DBExpService.CheckHealth:output_type -> dbexp.v1.CheckHealthResponse
	3, // 4: dbexp.v1.DBExpService.UpsertPost:output_type -> dbexp.v1.UpsertPostResponse
	5, // 5: dbexp.v1.DBExpService.ReadPost:output_type -> dbexp.v1.ReadPostResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dbexp_proto_init() }
func file_proto_dbexp_proto_init() {
	if File_proto_dbexp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dbexp_proto_rawDesc), len(file_proto_dbexp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dbexp_proto_goTypes,
		DependencyIndexes: file_proto_dbexp_proto_depIdxs,
		MessageInfos:      file_proto_dbexp_proto_msgTypes,
	}.Build()
	File_proto_dbexp_proto = out.File
	file_proto_dbexp_proto_goTypes = nil
	file_proto_dbexp_proto_depIdxs = nil
}
